import { Project } from "../types";
import { getImagePath } from "./utils";

/**
 * Datos de los proyectos que se muestran en el portafolio
 */
export const projects: Project[] = [
  {
    id: "suvey_cibersegurity",
    title: "Sistema de IA para Clasificación de Documentos de Ciberseguridad",
    challenge: "Las organizaciones de ciberseguridad enfrentan dificultades con grandes volúmenes de documentos no estructurados. La búsqueda manual es lenta, propensa a errores y obstaculiza la toma de decisiones rápidas durante incidentes.",
    solution: "RDI Document Processor automatiza el procesamiento y segmentación de documentos, almacenándolos en bases de datos vectoriales. Utilizando LangChain, ChromaDB y Pinecone, permite búsquedas semánticas rápidas y reduce el trabajo manual y los errores.",
    tech: [
      "JavaScript",
      "Node.js",
      "Express",
      "MongoDB (via Mongoose)",
      "dotenv",
      "LangChain",
      "OpenAI",
      "Pinecone",
      "ChromaDB",
      "Stripe",
      "axios",
      "bcrypt",
      "fs-extra",
      "mammoth",
      "express-session",
      "cors",
    ],
    liveUrl: "https://app.rdishield.com/",
    repoUrl: "",
    galleryImages: [
      getImagePath("projects/suvey_cibersegurity/screenshot-2025-07-08-093506.png"),
      getImagePath("projects/suvey_cibersegurity/screenshot-2025-07-08-093523.png"),
      getImagePath("projects/suvey_cibersegurity/screenshot-2025-07-08-093603.png"),
      getImagePath("projects/suvey_cibersegurity/screenshot-2025-07-08-093911.png"),
      getImagePath("projects/suvey_cibersegurity/screenshot-2025-07-08-094156.png"),
      getImagePath("projects/suvey_cibersegurity/screenshot-2025-07-08-094256.png"),
    ],
  },
  {
    id: "n8n-dulton-consultans",
    title: "Sistema CRM para Renovación Automatizada de Pólizas y Reportes",
    challenge: "Las compañías de seguros gestionan pólizas, clientes y renovaciones con sistemas fragmentados como hojas de cálculo y correos electrónicos. Esto causa demoras, errores y dificulta el seguimiento de oportunidades y el cumplimiento normativo.",
    solution: "La plataforma centraliza los datos de pólizas y clientes, automatiza renovaciones y notificaciones, y genera reportes en un solo entorno. Esto mejora la precisión, agiliza los procesos y aumenta la satisfacción del cliente.",
    tech: [
      "TypeScript",
      "Vue.js",
      "SCSS",
      "JavaScript",
      "Node.js",
      "Docker",
      "docker-compose",
      "PostgreSQL",
      "MariaDB",
      "MySQL",
      "Jest",
      "Cypress",
      "eslint",
      "turbo",
      "LangChain",
      "pnpm",
    ],
    liveUrl: "https://appdulton.com",
    repoUrl: "https://github.com/rg7services/n8n-dulton-consultans",
    galleryImages: [
      getImagePath("projects/dultos-consultans/screenshot-2025-07-08-090621.png"),
      getImagePath("projects/dultos-consultans/screenshot-2025-07-08-090650.png"),
      getImagePath("projects/dultos-consultans/screenshot-2025-07-08-090832.png"),
      getImagePath("projects/dultos-consultans/screenshot-2025-07-08-091156.png"),
    ],
  },
  {
    id: "professionalRestaurant",
    title: "Sistema Digital de Gestión de Pedidos y Mesas",
    challenge: "Los restaurantes enfrentan problemas con la toma manual de pedidos y la comunicación fragmentada entre el comedor y la cocina, lo que genera demoras, errores en los pedidos y falta de visibilidad de datos operativos para mejorar el servicio.",
    solution: "Elegant Dine digitaliza pedidos, reservas y el estado de las mesas con códigos QR y notificaciones en tiempo real. Proporciona reportes accionables utilizando Supabase para mejorar la coordinación, reducir errores y optimizar la experiencia del cliente.",
    tech: [
      "TypeScript",
      "React",
      "Vite",
      "TailwindCSS",
      "Supabase",
      "Lucide React",
      "Howler",
      "React Router DOM",
      "qrcode.react",
      "React Hot Toast",
      "React Datepicker",
      "Zustand",
      "ESLint",
      "PostCSS",
      "Autoprefixer",
      "PLpgSQL",
      "JavaScript",
    ],
    liveUrl: "https://especialdinner.netlify.app/",
    repoUrl: "",
    galleryImages: [
      getImagePath("projects/professionalRestaurant/screenshot-2025-07-08-101858.png"),
      getImagePath("projects/professionalRestaurant/screenshot-2025-07-08-101929.png"),
      getImagePath("projects/professionalRestaurant/screenshot-2025-07-08-102023.png"),
      getImagePath("projects/professionalRestaurant/screenshot-2025-07-08-102047.png"),
      getImagePath("projects/professionalRestaurant/screenshot-2025-07-08-102303.png"),
    ],
  },
  {
    id: "QREventProject",
    title: "Herramienta Simplificada de Gestión de Eventos y Análisis",
    challenge: "La gestión de registros y accesos a eventos suele ser manual y dispersa. La falta de visibilidad en tiempo real y datos consolidados dificulta la toma de decisiones y la experiencia de los asistentes.",
    solution: "QREventProject centraliza el registro de asistentes, genera y valida accesos con códigos QR y muestra métricas en tiempo real. Esto agiliza la gestión de eventos, reduce errores y proporciona datos clave para mejorar los eventos.",
    tech: [
      "TypeScript",
      "React",
      "Vite",
      "TailwindCSS",
      "Supabase",
      "Jest",
      "ESLint",
      "PostCSS",
      "date-fns",
      "dotenv",
      "React Hook Form",
      "React Router DOM",
      "Lucide React",
      "XLSX",
    ],
    liveUrl: "https://formularios.equipogctrade.com/",
    repoUrl: "",
    galleryImages: [
      getImagePath("projects/QrEvent/screenshot-2025-07-08-100400.png"),
      getImagePath("projects/QrEvent/screenshot-2025-07-08-100421.png"),
      getImagePath("projects/QrEvent/screenshot-2025-07-08-100441.png"),
      getImagePath("projects/QrEvent/screenshot-2025-07-08-100858.png"),
      getImagePath("projects/QrEvent/screenshot-2025-07-08-100911.png"),
      getImagePath("projects/QrEvent/screenshot-2025-07-08-100923.png"),
      getImagePath("projects/QrEvent/screenshot-2025-07-08-100934.png"),
      getImagePath("projects/QrEvent/screenshot-2025-07-08-105905.png"),
    ],
  },
  {
    id: "rg7_prh_front",
    title: "Plataforma para Seguimiento de Instalaciones POP en Tiendas",
    challenge: "La gestión de procesos de recursos humanos con múltiples herramientas y hojas de cálculo genera errores, datos dispersos y demoras en la generación de reportes críticos.",
    solution: "RG7 PRH Frontend unifica los flujos de trabajo de recursos humanos: autenticación segura, gestión de datos y generación de reportes (CSV, PDF, Excel). Mejora la trazabilidad, la eficiencia y la experiencia tanto para administradores como para empleados.",
    tech: [
      "React",
      "Vite",
      "Ant Design",
      "Tailwind CSS",
      "Auth0",
      "Axios",
      "jsPDF",
      "Moment.js",
      "react-csv",
      "react-datepicker",
      "react-datetime",
      "react-dom",
      "react-paginate",
      "react-router-dom",
      "react-select",
      "react-table",
      "sweetalert",
      "xlsx",
      "TypeScript (in subproject)",
      "PostCSS",
      "Autoprefixer",
    ],
    liveUrl: "https://front-prh.equipogctrade.com/",
    repoUrl: "",
    galleryImages: [
      getImagePath("projects/rg7_prh/screenshot-2025-07-08-115104.png"),
      getImagePath("projects/rg7_prh/screenshot-2025-07-08-115125.png"),
      getImagePath("projects/rg7_prh/screenshot-2025-07-08-115142.png"),
      getImagePath("projects/rg7_prh/screenshot-2025-07-08-115209.png"),
      getImagePath("projects/rg7_prh/screenshot-2025-07-08-115220.png"),
      getImagePath("projects/rg7_prh/screenshot-2025-07-08-115232.png"),
    ],
  },
  {
    id: "La Oleada Roja Legrand",
    title: "Sistema Centralizado de Distribución y Análisis de Material POP",
    challenge: "La gestión manual y descentralizada de campañas de branding y distribución de material POP (Punto de Venta) en múltiples tiendas genera ineficiencias. Esto incluye problemas de seguimiento, dificultad para medir el impacto de las campañas por área o agente, y oportunidades perdidas para futuras instalaciones. La falta de una visión consolidada impide la toma de decisiones estratégicas y la asignación eficiente de recursos.",
    solution: "La plataforma 'Legrand Oleada Roja' centraliza y digitaliza la distribución de materiales de branding y POP. Permite la geolocalización de tiendas, la asignación de agentes y el seguimiento detallado de los elementos instalados (banners, adhesivos de suelo, displays, etc.). Los paneles de control muestran métricas clave como el número de tiendas impactadas, materiales instalados por tienda y oportunidades para futuras instalaciones. Mejora la transparencia, la logística, la evaluación de rendimiento por área y agente, y optimiza la planificación de la visibilidad de la marca.",
    tech: [
      "React",
      "JavaScript",
      "Create React App",
      "Node.js",
      "Jest",
      "HTML",
      "CSS",
      "dotenv",
      "ESLint",
      "Webpack",
      "Babel",
    ],
    liveUrl: "https://front-legrand.equipogctrade.com/",
    repoUrl: "",
    galleryImages: [
      getImagePath("projects/legrand/screenshot-2025-07-08-144638.png"),
      getImagePath("projects/legrand/screenshot-2025-07-08-144651.png"),
      getImagePath("projects/legrand/screenshot-2025-07-08-144705.png"),
      getImagePath("projects/legrand/screenshot-2025-07-08-144824.png"),
      getImagePath("projects/legrand/screenshot-2025-07-08-144848.png"),
      getImagePath("projects/legrand/screenshot-2025-07-08-144857.png"),
      getImagePath("projects/legrand/screenshot-2025-07-08-144911.png"),
      getImagePath("projects/legrand/screenshot-2025-07-08-144923.png"),
    ],
  },
];