import { Project } from "../types";

/**
 * Datos de los proyectos que se muestran en el portafolio
 */
export const projects: Project[] = [
  {
    id: "suvey_cibersegurity",
    title: "RDI Document Processor",
    challenge:
      "Las organizaciones de ciberseguridad luchan con grandes volúmenes de documentos no estructurados. La búsqueda manual es lenta, propensa a errores y dificulta la toma de decisiones rápida ante incidentes.",
    solution:
      "RDI Document Processor automatiza el procesamiento y segmentación de documentos, almacenándolos en bases vectoriales. Con LangChain, ChromaDB y Pinecone, facilita consultas semánticas rápidas y reduce el trabajo manual y los errores.",
    tech: [
      "JavaScript",
      "Node.js",
      "Express",
      "MongoDB (via Mongoose)",
      "dotenv",
      "LangChain",
      "OpenAI",
      "Pinecone",
      "ChromaDB",
      "Stripe",
      "axios",
      "bcrypt",
      "fs-extra",
      "mammoth",
      "express-session",
      "cors",
    ],
    liveUrl: "https://app.rdishield.com/",
    repoUrl: "",
    galleryImages: [
      "/projects/suvey_cibersegurity/Screenshot 2025-07-08 093506.png",
      "/projects/suvey_cibersegurity/Screenshot 2025-07-08 093523.png",
      "/projects/suvey_cibersegurity/Screenshot 2025-07-08 093603.png",
      "/projects/suvey_cibersegurity/Screenshot 2025-07-08 093911.png",
      "/projects/suvey_cibersegurity/Screenshot 2025-07-08 094156.png",
      "/projects/suvey_cibersegurity/Screenshot 2025-07-08 094256.png",
    ],
  },
  {
    id: "n8n-dulton-consultans",
    title: "Dulton Consultans",
    challenge:
      "Las aseguradoras manejan pólizas, clientes y renovaciones en sistemas fragmentados: hojas de cálculo y correos. Esto provoca demoras, errores y dificulta un seguimiento efectivo de oportunidades y cumplimiento.",
    solution:
      "La plataforma centraliza datos de pólizas y clientes, automatiza renovaciones y notificaciones, y genera reportes en un solo entorno. Así, mejora la precisión, acelera procesos y eleva la satisfacción del cliente.",
    tech: [
      "TypeScript",
      "Vue.js",
      "SCSS",
      "JavaScript",
      "Node.js",
      "Docker",
      "docker-compose",
      "PostgreSQL",
      "MariaDB",
      "MySQL",
      "Jest",
      "Cypress",
      "eslint",
      "turbo",
      "LangChain",
      "pnpm",
    ],
    liveUrl: "https://appdulton.com",
    repoUrl: "https://github.com/rg7services/n8n-dulton-consultans",
    galleryImages: [
      "/projects/Dultos Consultans/Screenshot 2025-07-08 090621.png",
      "/projects/Dultos Consultans/Screenshot 2025-07-08 090650.png",
      "/projects/Dultos Consultans/Screenshot 2025-07-08 090832.png",
      "/projects/Dultos Consultans/Screenshot 2025-07-08 091156.png",
    ],
  },
  {
    id: "professionalRestaurant",
    title: "Professional Restaurant",
    challenge:
      "Los restaurantes enfrentan pedidos manuales y comunicación fragmentada entre salón y cocina, causando retrasos, errores en órdenes y falta de visibilidad de datos operativos para mejorar el servicio.",
    solution:
      "Elegant Dine digitaliza pedidos, reservas y estado de mesas con QR y notificaciones en tiempo real. Ofrece reportes accionables desde Supabase que optimizan coordinación, reducen errores y mejoran la experiencia del cliente.",
    tech: [
      "TypeScript",
      "React",
      "Vite",
      "TailwindCSS",
      "Supabase",
      "Lucide React",
      "Howler",
      "React Router DOM",
      "qrcode.react",
      "React Hot Toast",
      "React Datepicker",
      "Zustand",
      "ESLint",
      "PostCSS",
      "Autoprefixer",
      "PLpgSQL",
      "JavaScript",
    ],
    liveUrl: "https://especialdinner.netlify.app/",
    repoUrl: "",
    galleryImages: [
      "/projects/professionalRestaurant/Screenshot 2025-07-08 101858.png",
      "/projects/professionalRestaurant/Screenshot 2025-07-08 101929.png",
      "/projects/professionalRestaurant/Screenshot 2025-07-08 102023.png",
      "/projects/professionalRestaurant/Screenshot 2025-07-08 102047.png",
      "/projects/professionalRestaurant/Screenshot 2025-07-08 102303.png",
    ],
  },
  {
    id: "QREventProject",
    title: "Enterprise Event",
    challenge:
      "Gestionar registros y accesos en eventos suele ser manual y disperso. La falta de visibilidad en tiempo real y datos consolidados dificulta la toma de decisiones y la experiencia del asistente.",
    solution:
      "QREventProject centraliza registro de asistentes, genera y valida accesos con códigos QR, y muestra métricas en tiempo real. Esto agiliza la gestión, reduce errores y proporciona datos clave para mejorar eventos.",
    tech: [
      "TypeScript",
      "React",
      "Vite",
      "TailwindCSS",
      "Supabase",
      "Jest",
      "ESLint",
      "PostCSS",
      "date-fns",
      "dotenv",
      "React Hook Form",
      "React Router DOM",
      "Lucide React",
      "XLSX",
    ],
    liveUrl: "https://formularios.equipogctrade.com/",
    repoUrl: "",
    galleryImages: [
      "/projects/QrEvent/Screenshot 2025-07-08 100400.png",
      "/projects/QrEvent/Screenshot 2025-07-08 100421.png",
      "/projects/QrEvent/Screenshot 2025-07-08 100441.png",
      "/projects/QrEvent/Screenshot 2025-07-08 100858.png",
      "/projects/QrEvent/Screenshot 2025-07-08 100911.png",
      "/projects/QrEvent/Screenshot 2025-07-08 100923.png",
      "/projects/QrEvent/Screenshot 2025-07-08 100934.png",
      "/projects/QrEvent/Screenshot 2025-07-08 105905.png",
    ],
  },
  {
    id: "rg7_prh_front",
    title: "Penguin Random House",
    challenge:
      "La gestión de recursos humanos con múltiples herramientas y hojas de cálculo genera errores, datos dispersos y retrasos en la generación de reportes críticos.",
    solution:
      "RG7 PRH Frontend unifica el flujo de RH: autenticación segura, gestión de datos y generación de reportes (CSV, PDF, Excel). Así mejora la trazabilidad, eficiencia y experiencia de administradores y empleados.",
    tech: [
      "React",
      "Vite",
      "Ant Design",
      "Tailwind CSS",
      "Auth0",
      "Axios",
      "jsPDF",
      "Moment.js",
      "react-csv",
      "react-datepicker",
      "react-datetime",
      "react-dom",
      "react-paginate",
      "react-router-dom",
      "react-select",
      "react-table",
      "sweetalert",
      "xlsx",
      "TypeScript (en subproyecto)",
      "PostCSS",
      "Autoprefixer",
    ],
    liveUrl: "https://front-prh.equipogctrade.com/",
    repoUrl: "",
    galleryImages: [
      "/projects/rg7_prh/Screenshot 2025-07-08 115104.png",
      "/projects/rg7_prh/Screenshot 2025-07-08 115125.png",
      "/projects/rg7_prh/Screenshot 2025-07-08 115142.png",
      "/projects/rg7_prh/Screenshot 2025-07-08 115209.png",
      "/projects/rg7_prh/Screenshot 2025-07-08 115220.png",
      "/projects/rg7_prh/Screenshot 2025-07-08 115232.png",
    ],
  },
  {
    id: "rg7_ruleta",
    title: "Ruleta Frontend",
    challenge:
      "Los sorteos manuales carecen de transparencia y seguimiento. La experiencia es lenta y difícil de integrar en plataformas digitales, reduciendo la confianza del usuario.",
    solution:
      "Ruleta Frontend digitaliza sorteos con una interfaz interactiva, resultados en tiempo real y registro de participantes. Mejora la transparencia, la participación y facilita la integración en apps.",
    tech: [
      "React",
      "JavaScript",
      "Create React App",
      "Node.js",
      "Jest",
      "HTML",
      "CSS",
      "dotenv",
      "ESLint",
      "Webpack",
      "Babel",
    ],
    liveUrl: "https://ruleta-gc.equipogctrade.com/",
    repoUrl: "",
    galleryImages: [],
  },
];
